version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my_network
    depends_on:
      - web_server1
      - web_server2
      - mysql_server

  web_server1:
    build:
      context: ./web_server1
    container_name: web_server1
    volumes:
      - ./app1:/var/www/html
    networks:
      - my_network
    depends_on:
      - mysql_server

  web_server2:
    build:
      context: ./web_server2
    container_name: web_server2
    volumes:
      - ./app2:/var/www/html
    networks:
      - my_network
    depends_on:
      - mysql_server

  mysql_server:
    image: mysql:5.7
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - my_network
    volumes:
      - ./mysql-data:/var/lib/mysql

networks:
  my_network:
    driver: bridge
